-- MySQL Script generated by MySQL Workbench
-- Sat May 28 22:43:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restoratedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restoratedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restoratedb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `restoratedb` ;

-- -----------------------------------------------------
-- Table `restoratedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoratedb`.`users` (
  `user_id` INT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NULL,
  `gender` TINYINT(3) NULL,
  `password` VARCHAR(45) NULL,
  `favorites` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoratedb`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoratedb`.`restaurants` (
  `res_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `ratings` DECIMAL(10) NULL,
  `image` VARBINARY(255) NULL,
  `pricing` DECIMAL(10) NULL,
  PRIMARY KEY (`res_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoratedb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoratedb`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT NOT NULL,
  `restaurants_res_id` INT NOT NULL,
  `comments` LONGTEXT NULL,
  INDEX `fk_users_has_restaurants_restaurants1_idx` (`restaurants_res_id` ASC) VISIBLE,
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `fk_users_has_restaurants_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `restoratedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_restaurants_restaurants1`
    FOREIGN KEY (`restaurants_res_id`)
    REFERENCES `restoratedb`.`restaurants` (`res_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoratedb`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoratedb`.`reviews` (
  `review_id` VARCHAR(45) NOT NULL,
  `users_user_id` INT NOT NULL,
  `restaurants_res_id` INT NOT NULL,
  `review` VARCHAR(45) NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_users_has_restaurants_restaurants2_idx` (`restaurants_res_id` ASC) VISIBLE,
  INDEX `fk_users_has_restaurants_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_restaurants_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `restoratedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_restaurants_restaurants2`
    FOREIGN KEY (`restaurants_res_id`)
    REFERENCES `restoratedb`.`restaurants` (`res_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `restoratedb` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `restoratedb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
--  routine2
-- -----------------------------------------------------

DELIMITER $$
USE `restoratedb`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
